### PR TITLE
Adding some general security to the debates module views. 

### PR DESCRIPTION
**Pull request by dhritimanh**
It will be soon updated though. Still not good enough.

### CODE REVIEW

**Comment by oscarcp** [comment]
I'm sorry I don't quite understand the modifications you have done to enhance security in the debates module. Can you explain in a comment? :)

**Comment by dhritimanh** [comment]
Hello,
The problem was that a user who is not logged in can view debates of a *
non-public\* space by doing something like <space_name>/debate etc. and also
<space_name>/debate/2 etc .. It was solved. That login_reqd decorator is
useless ... I know . I was testing something i guess . But now some bugs
are solved related to debates of the non-public spaces.
Thanks and Regards

**Comment by dhritimanh** [comment]
Hello Oscar, If u can , Please do Come to chat in gmail and i can explain
it in real time as i implement something .

**Comment by dhritimanh** [comment]
I have been doing the spaces and the debates and its various views .. Thinking of assisting in ticket 81 too .. Lets see .. Its exciting times .. :)

**Comment by dhritimanh** [comment]
I am sorry for the confusion. I will make sure i write comments for a block
of code from now on.
Thanks

**Comment by oscarcp** [comment]
Closing because of GSOC cleaning process

**Pull request closed without merging**
